---
title: 'Habitat data extraction and visualization'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '../../../ohiprep_v2018/src/templates/ohi_hdr.html'
  pdf_document:
    toc: true
editor_options: 
  chunk_output_type: console
---


## set up

```{r setup, message=FALSE, warning=FALSE, verbose=FALSE}

#set options for all chunks in code
knitr::opts_chunk$set(warning=FALSE, message=FALSE,fig.width=6, fig.height=6)

#libraries
library(dplyr)
library(tidyr)

library(googleVis)
library(ggplot2)
library(plotly)
library(htmlwidgets)
library(RColorBrewer)

library(raster)

library(ohicore)

library(doParallel)
library(foreach)
library(parallel)

source("https://raw.githubusercontent.com/OHI-Science/ohiprep_v2018/master/src/R/spatial_common.R")

cols = rev(colorRampPalette(brewer.pal(11, 'Spectral'))(255)) # rainbow color scheme


```

## Sea ice check
Unclear how to best extract sea ice habitat data because this is on a continuous scale.  

```{r}

ice_habs <- list.files(file.path(dir_M, "git-annex/impact_acceleration/seaice/masks"), full=TRUE)

chi <- list.files(file.path(dir_M, "git-annex/impact_acceleration/impact/cumulative_impact"), full=TRUE, pattern = "chi")

chi_stack <- stack(chi)


for(ice_hab in ice_habs) { # ice_hab = ice_habs[1]

  habitat_name <- gsub(".tif", "", basename(ice_hab))
  
  zone <- raster::raster(ice_hab)
  
hab_data <- raster::zonal(chi_stack, zone, fun="mean", progress="text", na.rm=TRUE)

hab_data_df <- data.frame(hab_data) %>%
  tidyr::gather("pressure", "value", -1) %>%
  dplyr::rename("habitat" = zone) %>%
  dplyr::mutate(year = as.numeric(substring(pressure, 5, 8))) %>%
  dplyr::mutate(pressure = "chi") %>%
  dplyr::mutate(habitat=habitat_name)

write.csv(hab_data_df, sprintf("habitats/mask_explore/%s_chi.csv", habitat_name), row.names=FALSE)
}


filenames <- list.files("habitats/mask_explore", full=TRUE)
datalist = lapply(filenames, function(x){read.csv(file=x,header=T)})

ice_edge_chi <- bind_rows(datalist)

```

## Habitat zones

```{r}

habs <- list.files(file.path(dir_M, "git-annex/impact_acceleration/habitats"), full=TRUE)
habs <- habs[-(grep(".vat.dbf|.xml|.ovr", habs))]
habs <- habs[-(grep("ice", habs))]
ice <- file.path(dir_M, "git-annex/impact_acceleration/seaice/masks/ice.tif")
habs <- c(habs, ice)
```




## Chi data

```{r}

chi <- list.files(file.path(dir_M, "git-annex/impact_acceleration/impact/cumulative_impact"), full=TRUE, pattern = "chi")

chi_stack <- stack(chi)

registerDoParallel(4)

foreach(hab = habs,.packages="dplyr")%dopar% { # hab = habs[21]
#for(hab in habs){
  
  habitat_name <- gsub(".tif", "", basename(hab))
  
  zone <- raster::raster(hab)
  
hab_data <- raster::zonal(chi_stack, zone, fun="mean", progress="text", na.rm=TRUE)

hab_data_df <- data.frame(hab_data) %>%
  tidyr::gather("pressure", "value", -1) %>%
  dplyr::rename("habitat" = zone) %>%
  dplyr::mutate(year = as.numeric(substring(pressure, 5, 8))) %>%
  dplyr::mutate(pressure = "chi") %>%
  dplyr::mutate(habitat=habitat_name)

write.csv(hab_data_df, sprintf("impacts/zonal_data_habitat/%s_chi.csv", habitat_name), row.names=FALSE)
}

```

## CHI Trend data

```{r}

# tmp <- raster(file.path(dir_M, "git-annex/impact_acceleration/hab_stressor_combo/sst__ice__2013.tif"))
# plot(tmp)
# 
# tmp <- raster(file.path(dir_M, "git-annex/impact_acceleration/hab_stressor_combo/art_fish__ice__2013.tif"))
# plot(tmp)

# tmp <- raster(file.path(dir_M, "git-annex/impact_acceleration/hab_stressor_combo/sst__inttidalmud__2003.tif"))
# plot(tmp)

trend <- raster(file.path(dir_M, "git-annex/impact_acceleration/trend/chi_slope.tif"))

hab_data_df <- data.frame()

for(hab in habs){ #hab=habs[7]
  
  habitat_name <- gsub(".tif", "", basename(hab))
  
  zone <- raster::raster(hab)
  
hab_data <- raster::zonal(trend, zone, fun="mean", progress="text", na.rm=TRUE)

hab_data_tmp <- data.frame(hab_data) %>%
  dplyr::rename("habitat" = zone) %>%
  dplyr::mutate(habitat=habitat_name)

hab_data_df <- rbind(hab_data_tmp, hab_data_df)

}

write.csv(hab_data_df, "impacts/zonal_data_habitat/chi_trend.csv", row.names=FALSE)

```

## Impacts trend extract

```{r}

impact_trends <- list.files(file.path(dir_M, "git-annex/impact_acceleration/trend/impacts"), full=TRUE)

registerDoParallel(4)

foreach(impact = impact_trends,.packages="dplyr")%dopar% { # impact = impact_trends[1]

impact_name <- basename(impact)
impact_name <- gsub("_trend.tif", "", impact_name)  

trend <- raster::raster(impact)
  
hab_data_df <- data.frame()

for(hab in habs){ # hab=habs[11]
  
  habitat_name <- gsub(".tif", "", basename(hab))
  
  zone <- raster::raster(hab)
  
hab_data <- raster::zonal(trend, zone, fun="mean", na.rm=TRUE)

hab_data_tmp <- data.frame(hab_data) %>%
  dplyr::rename("habitat" = zone) %>%
  dplyr::mutate(habitat=habitat_name)

hab_data_df <- rbind(hab_data_tmp, hab_data_df)


}
hab_data_df$impact <- impact_name
write.csv(hab_data_df, sprintf("impacts/zonal_data_habitat/%s_trend.csv", impact_name), row.names=FALSE)
}



```

## Impact extract
I don't think I will need these, but will keep code here in case.
```{r}

########### Years

years <- 2003:2013

years_subset <- paste(years, collapse="|")


####### Stressors
stress_files <- list.files(file.path(dir_M, "git-annex/impact_acceleration/stressors"), recursive = TRUE, 
           pattern = ".tif", full="TRUE")
stress_files <- grep("/final/", stress_files, value=TRUE)

#filter to relevant years
stress_files <- grep(years_subset, stress_files, value=TRUE)

stress_stack <- stack(stress_files)

#foreach(hab = habs,.packages="dplyr")%dopar% { # hab = habs[1]
for(hab in habs){ # hab <- habs[1]
  
  habitat_name <- gsub(".tif", "", basename(hab))
  
  zone <- raster::raster(hab)
  
hab_data <- raster::zonal(stress_stack, zone, fun="mean", progress="text", na.rm=TRUE)

hab_data_df <- data.frame(hab_data) %>%
  tidyr::gather("pressure", "value", -1) %>%
  dplyr::rename("habitat" = zone) %>%
  dplyr::mutate(pressure = gsub("_rescaled_mol", "", pressure)) %>%
  dplyr::mutate(year = as.numeric(stringr::str_sub(pressure, -4,-1))) %>%
  dplyr::mutate(pressure = stringr::str_sub(pressure, 1, stringr::str_length(pressure)-5)) %>%
  dplyr::mutate(habitat=habitat_name)

write.csv(hab_data_df, sprintf("impacts/zonal_data_habitat/%s_stressor.csv", habitat_name), row.names=FALSE)
}

```




## Stressor extract
I don't think I will need these, but will keep code here in case.
```{r}

########### Years

years <- 2003:2013

years_subset <- paste(years, collapse="|")


####### Stressors
stress_files <- list.files(file.path(dir_M, "git-annex/impact_acceleration/stressors"), recursive = TRUE, 
           pattern = ".tif", full="TRUE")
stress_files <- grep("/final/", stress_files, value=TRUE)

#filter to relevant years
stress_files <- grep(years_subset, stress_files, value=TRUE)

stress_stack <- stack(stress_files)

#foreach(hab = habs,.packages="dplyr")%dopar% { # hab = habs[1]
for(hab in habs){ # hab <- habs[1]
  
  habitat_name <- gsub(".tif", "", basename(hab))
  
  zone <- raster::raster(hab)
  
hab_data <- raster::zonal(stress_stack, zone, fun="mean", progress="text", na.rm=TRUE)

hab_data_df <- data.frame(hab_data) %>%
  tidyr::gather("pressure", "value", -1) %>%
  dplyr::rename("habitat" = zone) %>%
  dplyr::mutate(pressure = gsub("_rescaled_mol", "", pressure)) %>%
  dplyr::mutate(year = as.numeric(stringr::str_sub(pressure, -4,-1))) %>%
  dplyr::mutate(pressure = stringr::str_sub(pressure, 1, stringr::str_length(pressure)-5)) %>%
  dplyr::mutate(habitat=habitat_name)

write.csv(hab_data_df, sprintf("impacts/zonal_data_habitat/%s_stressor.csv", habitat_name), row.names=FALSE)
}

```


## Combine habitat chi data

```{r}

habs <- list.files("zonal_data_habitat", full=TRUE, pattern="_chi")

habitat_chi <- data.frame()

for(hab in habs){ # hab=habs[1]
  tmp <- read.csv(hab)
  habitat_chi <- rbind(habitat_chi, tmp)
}

write.csv(habitat_chi, "zonal_data_habitat/habitat_chi.csv", row.names=FALSE)

```



