---
title: 'Figures'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '../../ohiprep_v2018/src/templates/ohi_hdr.html'
  pdf_document:
    toc: true
---

```{r}
library(tidyr)
library(dplyr)
library(raster)
library(RColorBrewer)
library(tidyverse)
library(rgdal)
library(sf)
library(gstat)
library(stringr)
library(fields)
library(cowplot)

# load spatial files (ocean raster and regions shapefile)

source("https://raw.githubusercontent.com/OHI-Science/ohiprep_v2018/master/src/R/spatial_common.R")

regions_shape <- as(regions, "Spatial")
land <- regions_shape[regions_shape$rgn_type %in% c("land", "land-disputed", "land-noeez", "eez-inland"), ]


cols = rev(colorRampPalette(brewer.pal(11, 'Spectral'))(255)) # rainbow color scheme

```

# Plot of CHI

```{r}

## function to make plots

legend.shrink <- 0.7
legend.width <- 0.6


raster_breaks <- function(raster_data, title, title_legend=NULL, myBreaks, cols){
  par(mar=c(2,2,2,2)) # bottom, left, top, and right
  par(oma=c(0,0,0,0))
plot(raster_data, col=cols, axes=FALSE, box=FALSE, breaks=myBreaks, legend=FALSE)
  title(title, line=0)
# add axis with fields package function:
def_breaks <- seq(0, length(myBreaks), length.out=length(myBreaks))
image.plot(raster_data, #zlim = c(min(myBreaks), max(myBreaks)), 
           legend.only = TRUE, 
           legend.shrink=legend.shrink,
           legend.width=legend.width,
           col = cols,
           legend.lab=title_legend,
            breaks=def_breaks,
           lab.breaks=c(0, NA, 0.2, NA, 0.6, NA, 1, NA, 1.5, NA, 2, NA, 3, NA, 4.0, NA, ">5"),
           axis.args = list(cex.axis = 0.6))

plot(land, add=TRUE, border="gray80", col="gray90", lwd=0.5)
#plot(raster_data, col=cols, axes=FALSE, box=FALSE, breaks=myBreaks, legend=FALSE, add=TRUE)
}

my_breaks <- c(-1, 0, 0.2, 0.4, 0.6, 0.8, 1, 1.25, 1.5, 1.75, 2, 2.5, 3, 3.5, 4.0, 5, 100) 
cols = rev(colorRampPalette(brewer.pal(11, 'Spectral'))(length(my_breaks)-1)) #(length(my_breaks)-2))


for(year in 2003:2013){ # year = 2013
png(sprintf("impacts/figures/chi_maps/chi_%s.png", year), res=600, width=6, height=3, units="in")  
p_rast <- raster(file.path(dir_M, sprintf("git-annex/impact_acceleration/impact/cumulative_impact/chi_%s.tif", year)))
raster_breaks(raster_data=p_rast,  
              myBreaks=my_breaks, cols=cols, title="")
dev.off()
}


```

# Plot map of trend

```{r}

slope <- raster(file.path(dir_M, 'git-annex/impact_acceleration/trend/chi_slope.tif'))
overlay_rast <- raster(file.path(dir_M,  'git-annex/impact_acceleration/trend/sig_overlay.tif'))


cols = rev(colorRampPalette(c("#9E0142", "#9E0142", "#9E0142", "#9E0142", "#D53E4F", "#D53E4F", "#D53E4F", "#F46D43", "#F46D43", "#FDAE61", "#FDAE61",             
              "#FFFFBF", "#FFFFBF",  
             "#66C2A5", "#66C2A5", "#3288BD", "#3288BD", "#5E4FA2", "#5E4FA2",  "#5E4FA2"))(255)) # 

png("impacts/figures/trend/chi_trend.png", res=600, width=6, height=3, units="in")  
par(mar=c(2, 2, 2, 2))
par(oma=c(0,0,0,0))
plot(slope, col=cols, axes=FALSE, box=FALSE, legend=FALSE)
plot(overlay_rast, col="#ffffff", add=TRUE, legend=FALSE, box=FALSE)
plot(land, add=TRUE, border="gray80", col="gray90", lwd=0.5)
par(mfrow=c(1, 1), mar=c(2, 0, 1, 0), new=FALSE)
plot(slope, legend.only=TRUE, legend.shrink=.7, legend.width=.5, col=cols, axis.args = list(cex.axis = 0.6))
dev.off()

```

# CHI quantile plot

## Organize the quantile data

```{r}

files <- list.files("impacts/quantiles", full=TRUE, pattern=".csv")

filter_str <- function(stressor){ #stressor <- "art_fish"
stress_files <- grep(stressor, files, value=TRUE)

all_data <- c()
for (file in stress_files){ # file = stress_files[1]
  little_data <- read.csv(file)
  all_data <- rbind(all_data, little_data)
}

all_data$year <- as.numeric(str_sub(all_data$impact,-8,-5))
all_data
}

```

### Plot the CHI data
```{r}
library(ggrepel)

quant_names <- data.frame(quant = c("quant_1", "quant_5", "quant_50", "quant_95", "quant_99"),
                          new_name =c("1th", "5th", "50th", "95th", "99th"))

plot_data <- filter_str(stressor="chi") %>%
  mutate(quant = gsub("%", "", quant)) %>%
  mutate(quant = paste0("quant_", quant)) %>%
  filter(quant %in% c("quant_5", "quant_50", "quant_95", "quant_99")) %>%
  left_join(quant_names) %>%
  mutate(label = if_else(year == max(year), as.character(new_name), NA_character_)) %>%
  mutate(quants_plus = quants+0.4)

lvls <- unique(plot_data$year)

ggplot(plot_data, aes(x=as.factor(year), y=quants, group=quant, col=quant)) +
#  geom_point(size=3, alpha=0.7) +
  geom_line(alpha=0.7, size=2) +
  labs(x="Year", y="Cumulative human impact", title="Global quantiles") +
  scale_x_discrete(breaks = lvls[seq(1, length(lvls), by=2)]) +
  geom_text_repel(aes(label = label), na.rm=TRUE, nudge_x=-0.3, point.padding = unit(8, "points"), nudge_y = 0.1, size=4.5, segment.color=NA) +
  scale_color_discrete(guide = FALSE) +
  theme(plot.title = element_text(face="plain", hjust=0.88, size=13))

ggsave("impacts/figures/quants/chi_global_quants.png", width=6, height=5, units=c("in"), dpi=300)

```


# Trend for each eez impact barplot

```{r}

# get data
un_rgn <- UNgeorgn_nm %>%
  dplyr::select(rgn_id, georegion = r1_label)

chi <- read.csv("impacts/zonal_data_eez/eez_chi_trend.csv") %>%
  dplyr::select(rgn_id, rgn_name, chi=value) %>%
  left_join(un_rgn, by="rgn_id")


# rank of georegions
rank_georgn <- chi %>%
  group_by(georegion) %>%
  summarize(mean_chi = mean(chi),
            count = length(chi)) %>%
  arrange(mean_chi)

chi$georegion <- factor(chi$georegion, levels=rank_georgn$georegion)

rank_rgn <- chi %>%
  arrange(georegion, chi)

rank_rgn <- rank_rgn %>%
  mutate(rgn_name_short = rgn_name, 
         rgn_name_short = gsub("Islands", "Isl", rgn_name_short),
         rgn_name_short = gsub("Island", "Isl", rgn_name_short),
         rgn_name_short = gsub("Democratic", "Dem", rgn_name_short),
         rgn_name_short = gsub("Republic", "Rep", rgn_name_short),
         rgn_name_short = gsub("South", "S", rgn_name_short),
         rgn_name_short = gsub("American", "Am", rgn_name_short),
         rgn_name_short = gsub("the United States", "US", rgn_name_short),
         rgn_name_short = gsub("Territory", "Terr", rgn_name_short),
         rgn_name_short = gsub("Saint", "St", rgn_name_short),
         rgn_name_short = gsub(" and ", " & ", rgn_name_short),
         rgn_name_short = gsub("Republique", "Rep", rgn_name_short),
         rgn_name_short = gsub("Dem Rep of the", "Dem Rep of", rgn_name_short),
         rgn_name_short = gsub("Georgia and the", "Georgia and", rgn_name_short),
         rgn_name_short = gsub("St Vincent and the", "St Vincent and", rgn_name_short),
         rgn_name_short = gsub("Howland Isl & Baker Isl", "Howland & Baker Isl", rgn_name_short),
         rgn_name_short = gsub("Northern", "N", rgn_name_short), 
         rgn_name_short = gsub("Reunion", "Reunion                 ", rgn_name_short))


# some code to orient the country labels
sequence_length = length(unique(impacts$rgn_name))
first_sequence = c(1:(sequence_length%/%2)) 
second_sequence = c((sequence_length%/%2+1):sequence_length) 
first_angles = c(90 - 180/length(first_sequence) * first_sequence)
second_angles = c(-90 - 180/length(second_sequence) * second_sequence)

rank_rgn$id <- 1:220
rank_rgn$angle <- c(first_angles,second_angles)

########### marking georegions
# add column to identify when georegion changes
rgn_shift <- rank_rgn %>%
  mutate(region_shift = as.numeric(georegion) - lag(as.numeric(georegion), default=first(as.numeric(georegion))))

rgn_shift <- which(rgn_shift$region_shift > 0)
rgn_shift <- c(1, rgn_shift) -0.5

# dataframe to add base lines
base_data=rank_rgn %>%
  mutate(id = rep( seq(1, nrow(rank_rgn)))) %>%
  group_by(georegion) %>%
  summarize(start=min(id), end=max(id)) %>%
  rowwise() %>%
  mutate(title=mean(c(start, end)))

# ###########
# # alternatively add extra row for each georegion
# empty_bar=1
# to_add = data.frame( matrix(NA, empty_bar*nlevels(rank_georgn$georegion), ncol(chi)) )
# colnames(to_add) = colnames(chi)
# to_add$georegion=rep(levels(rank_georgn$georegion), each=empty_bar)
# 
# #######
# # ranking of regions
# combine_rank_rgn <- rbind(chi, to_add) 

# rank_rgn <- combine_rank_rgn %>%
#   arrange(georegion, -chi) %>%
#     mutate(id = seq(1, nrow(combine_rank_rgn)))
  
# organize impact data
impacts <- read.csv("impacts/zonal_data_eez/eez_impacts_trend.csv") %>%
  left_join(un_rgn)

## shorten rgn names

# ## add some blanks to separate groups
# empty_bar <- 4
# to_add <-  data.frame( matrix(NA, empty_bar*nlevels(rank_georgn$georegion)*nlevels(as.factor(impacts$pressure)), ncol(impacts)) )
# colnames(to_add) <- colnames(impacts)
# to_add$georegion <- rep(levels(rank_georgn$georegion), each=empty_bar)
# to_add$pressure <- rep(levels(as.factor(impacts$pressure)), each=empty_bar)
# to_add$value <-  0
# 
# impacts <- rbind(impacts, to_add) 

# impacts <- impacts %>%
#   left_join(dplyr::select(rank_rgn, rgn_id, id, georegion))
# 
# impacts$id <- factor(impacts$id, levels=rank_rgn$id)
# impacts <- impacts %>%
#   arrange(id)

impacts$rgn_name <- factor(impacts$rgn_name, levels=unique(rank_rgn$rgn_name))


## rank of pressure categories
impacts %>%
  group_by(pressure) %>%
  summarize(mean = mean(value))

pressure_name <- data.frame(pressure = c("sst", "oa", "slr", 
                                                  "shipping",
                                                  "nutrient", "organic", "direct_human", "light",
                                                  "pel_hb", "pel_lb", "dem_dest", "dem_nondest_hb",
                                                  "dem_nondest_lb", "art_fish"),
                            pressure_name = c("sst", "oa", "slr", 
                                              "shipping", 
                                              "nutrient pollution", "organic pollution", "direct human", "light pollution",
                                              "comm fish: pel hb", "comm fish: pel lb", "comm fish: dem dest", 
                                              "comm fish: dem nondest hb", "comm fish: dem nondest lb",
                                              "artisanal fishing"))
impacts <- impacts %>%
  left_join(pressure_name, by = "pressure")

impacts$pressure_name <- factor(impacts$pressure_name, levels=rev(pressure_name$pressure_name))



library(beyonce)

myPalette <- c(beyonce_palette(18, 15, type=c("continuous"))[1:6],
               beyonce_palette(18, 25, type=c("continuous"))[15:18],
               beyonce_palette(18, 15, type=c("continuous"))[8],
               beyonce_palette(18, 20, type=c("continuous"))[16:19])
               

p <- ggplot(data=impacts, aes(x=fct_reorder(rgn_name, id), y=value, fill=pressure_name)) + 
  geom_bar(stat="identity") +
  scale_fill_manual(values=myPalette) +
  coord_flip() +
  theme_bw() +
  labs(y="Average change in impact per year", x="") + 
  guides(fill=guide_legend(reverse=TRUE)) +
  theme(axis.text.y=element_text(size=10),
        legend.justification=c(1,0), legend.position=c(0.3,0), legend.title = element_blank()) +
  geom_point(data=chi, aes(y=chi, x=rgn_name), fill="black", shape="|", size=2.5) + 
  geom_hline(yintercept=0, color="black") +
  geom_vline(xintercept=c(rgn_shift - 0.5), color="gray") +
  annotate("text", y=0.1, x=(c(rgn_shift, 220) -2), label=c(as.character(rank_georgn$georegion)), size=5)
p
ggsave('impacts/figures/trend/eez_trend_barplot.jpg', height=25, width=10)


## some theme stuff to make the plot look nice

#ax <- length(unique(impacts$rgn_name))
circle_theme <- theme(axis.line=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.position="none",
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.background=element_blank(),
      axis.text.x = element_blank())

# circle plot
# https://www.r-graph-gallery.com/299-circular-stacked-barplot/
p <- ggplot(data=impacts, aes(x=rgn_name, y=value, fill=pressure_name)) + 
  geom_bar(stat="identity") +
  scale_fill_manual(values=myPalette) +
  coord_polar() +
  geom_hline(yintercept=0, color="black") +
 geom_vline(xintercept=rgn_shift, color="gray") +
  geom_text(data=rank_rgn, aes(x=id, y=0.17, label=rgn_name_short, angle=angle), inherit.aes = FALSE) +
  #geom_point(data=chi, aes(y=chi, x=rgn_name), fill="black", shape="|", size=2.5) +
#  geom_segment(data=base_data, aes(x = start + 3, y = -0.015, xend = end-3, yend = -0.015), colour = "black", alpha=0.8, size=0.6 , inherit.aes = FALSE )  +
#  geom_text(data=base_data, aes(x = title, y = -18, label=group), hjust=c(1,1,0,0), colour = "black", alpha=0.8, size=4, fontface="bold", inherit.aes = FALSE) +
  circle_theme

p
ggsave('impacts/figures/trend/eez_trend_circleplot.jpg', height=18, width=18, units=c("in"))


  theme_bw() +
  labs(y="Average change in impact per year", x="") + 
  guides(fill=guide_legend(reverse=TRUE)) +
  theme(axis.text.y=element_text(size=10),
        legend.justification=c(1,0), legend.position=c(0.3,0), legend.title = element_blank()) +
  geom_point(data=chi, aes(y=chi, x=rgn_name), fill="black", shape="|", size=2.5) + 
  annotate("text", y=0.1, x=(c(rgn_shift, 220) -2), label=c(as.character(rank_georgn$georegion)), size=5)


```



### Habitat CHI heat map

```{r}
hab_data <- read.csv("impacts/zonal_data_habitat/habitat_chi.csv")

hab_names <- read.csv("habitats/habitat.csv") %>%
  dplyr::select(habitat=tif_name, name=plot_name2)

# combine habitats with same raster locations
hab_data <- hab_data %>%
  left_join(hab_names) %>%
  group_by(name, year) %>%
  summarize(value = mean(value))
  
  
avg_data <- hab_data %>%
  group_by(name) %>%
  summarize(average=mean(value)) %>%
  arrange(average)
  

hab_data$name <- factor(hab_data$name, 
                             levels = avg_data$name)


#cols = rev(colorRampPalette(brewer.pal(11, 'Spectral'))(255)) # 
cols = rev(colorRampPalette(c("#9E0142", "#9E0142", "#9E0142", "#9E0142", 
                              "#D53E4F", "#D53E4F", "#D53E4F", 
                              "#F46D43", "#F46D43", "#F46D43", 
                              "#F88D51", "#F88D51",
                              "#FDAE61", "#FDAE61", 
                              "#FED690", "#FED690",             
                               
                              "#FFFFBF", "#FFFFBF",   "#FFFFBF",
                              
                              "#66C2A5",  
                              "#3288BD", "#3288BD", 
                              "#5E4FA2",  "#5E4FA2"))(255)) # 


tmp <- ggplot(hab_data, aes(y=year, x=name)) +
  geom_tile(aes(fill=value, 
                text=sprintf("habitat: %s \nyear: %s \npressure: %s" , name, year, round(value, 2))), color="white") +
  scale_fill_gradientn(colors=cols, name="Impact") +
  ylab("") +
  xlab("") +
  theme_bw() + 
  scale_y_continuous(breaks=c(2003, 2005, 2007, 2009, 2011, 2013)) +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text.x=element_text(angle=45, hjust=1, vjust=1, size=13),
        axis.text.y=element_text(size=13)) 
tmp
ggsave("impacts/figures/habitat/carpet_plot_habitat.png", width=8, height=5, units=c("in"), dpi=300)

```

## Habitat Trend and CHI summary
```{r}


filenames <- list.files("impacts/zonal_data_habitat", pattern="chi.csv", full=TRUE)
datalist = lapply(filenames, function(x){read.csv(file=x,header=T)})

hab_chi <- rbind_all(datalist) %>%
  group_by(habitat) %>%
  summarize(chi_average=mean(value))

hab_data <- read.csv("impacts/zonal_data_habitat/chi_trend.csv") %>%
  rename(trend = mean) %>%
  left_join(hab_chi, by="habitat") %>%
  arrange(chi_average)

hab_names <- read.csv("habitats/habitat.csv") %>%
  dplyr::select(habitat=tif_name, name=plot_name2)

# combine habitats with same raster locations
hab_data <- hab_data %>%
  left_join(hab_names) %>%
  group_by(name) %>%
  summarize(trend = mean(trend),
            chi = mean(chi_average))

  
library(ggrepel)
library(cowplot)
ggplot(hab_data, aes(x=chi, y=trend)) +
  geom_point(size=5, alpha=0.5) +
  geom_text_repel(aes(label = name),
                 # box.padding   = 0.35, 
                #  point.padding = 0.5,
                  segment.color = 'grey50',
                segment.size = 0.2,
                point.padding = 0.2,
                size = 4) +
  labs(x = "Cumulative human impact", y = "Trend, cumulative human impact")

ggsave("impacts/figures/avg_chi_vs_trend_habitat.png", width=8, height=5, units=c("in"), dpi=300)

```



# Trend for each eez impact barplot

```{r}

chi_data <- read.csv("impacts/zonal_data_habitat/chi_trend.csv")

hab_names <- read.csv("habitats/habitat.csv") %>%
  dplyr::select(habitat=tif_name, name=plot_name2)

hab_data <- chi_data %>%
  left_join(hab_names) %>%
  group_by(name) %>%
  summarize(chi = mean(mean)) %>%
  arrange(chi)
  
## individual stressor data
filenames <- list.files("impacts/zonal_data_habitat", pattern="trend.csv", full=TRUE)
filenames <- filenames[-grep("chi", filenames)]
datalist = lapply(filenames, function(x){read.csv(file=x,header=T)})

hab_trend <- rbind_all(datalist) %>%
  left_join(hab_names) %>%
  group_by(name, impact) %>%
  summarize(trend = mean(mean))

hab_trend$name <- factor(hab_trend$name, levels=hab_data$name)


# some code to orient the country labels
sequence_length = length(unique(hab_trend$name))
first_sequence = c(1:(sequence_length%/%2)) 
second_sequence = c((sequence_length%/%2+1):sequence_length) 
first_angles = c(90 - 180/length(first_sequence) * first_sequence)
second_angles = c(-90 - 180/length(second_sequence) * second_sequence)

hab_data$id <- 1:16
hab_data$angle <- c(first_angles,second_angles)
hab_data$hjust <- c(rep(0, length(first_sequence)), 
                    rep(1, length(second_sequence)))


## rank of pressure categories
hab_trend %>%
  group_by(impact) %>%
  summarize(mean = mean(trend)) %>%
  arrange(mean)

impact_name <- data.frame(impact = c("sst", "oa", "slr", 
                                                  "shipping",
                                                  "nutrient", "organic", "direct_human", "light",
                                                  "pel_hb", "pel_lb", "dem_dest", "dem_nondest_hb",
                                                  "dem_nondest_lb", "art_fish"),
                            impact_name = c("sst", "oa", "slr", 
                                              "shipping", 
                                              "nutrient pollution", "organic pollution", "direct human", "light pollution",
                                              "comm fish: pel hb", "comm fish: pel lb", "comm fish: dem dest", 
                                              "comm fish: dem nondest hb", "comm fish: dem nondest lb",
                                              "artisanal fishing"))
hab_trend <- hab_trend %>%
  left_join(impact_name, by = "impact")

hab_trend$impact_name <- factor(hab_trend$impact_name, levels=rev(impact_name$impact_name))

library(beyonce)

myPalette <- c(beyonce_palette(18, 15, type=c("continuous"))[1:6],
               beyonce_palette(18, 25, type=c("continuous"))[15:18],
               beyonce_palette(18, 15, type=c("continuous"))[8],
               beyonce_palette(18, 20, type=c("continuous"))[16:19])
               

## some theme stuff to make the plot look nice
circle_theme <- theme(axis.line=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.position="none",
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.background=element_blank(),
      axis.text.x = element_blank())

# circle plot
# https://www.r-graph-gallery.com/299-circular-stacked-barplot/
p <- ggplot(data=hab_trend, aes(x=name, y=trend, fill=impact_name)) + 
  geom_bar(stat="identity") +
  geom_errorbar(aes(x = 1, ymin = -0.04, ymax=0.20), alpha=0)  +
  scale_fill_manual(values=myPalette) + 
  coord_polar() +
  geom_hline(yintercept=0, color="black") +
  geom_text(data=hab_data, aes(x=name, y=0.09, label=name, angle=angle+10, hjust=hjust), inherit.aes = FALSE) +
  circle_theme

p

ggsave('impacts/figures/trend/habitat_trend_circleplot.jpg', height=6, width=6, units=c("in"))


p <- ggplot(data=hab_trend, aes(x=name, y=trend, fill=impact_name)) + 
  geom_bar(stat="identity") +
  geom_errorbar(aes(x = 1, ymin = -0.04, ymax=0.05), alpha=0)  +
  scale_fill_manual(values=myPalette) + 
  coord_polar() +
  geom_hline(yintercept=0, color="black") +
  geom_text(data=hab_data, aes(x=name, y=0.08, label=name, angle=angle+10), inherit.aes = FALSE, hjust=0) + 
  theme(legend.title=element_blank()) +
  theme_bw()

leg <- cowplot::get_legend(p)
plot(leg)


ggsave('impacts/figures/trend/legend_circleplot.jpg', height=6, width=6, units=c("in"))


```


# line plots of EEZ CHI
```{r}

un_rgn <- UNgeorgn_nm %>%
  dplyr::select(rgn_id, georegion = r1_label)

chi <-read.csv("impacts/zonal_data_eez/eez_chi.csv")  %>%
  dplyr::select(rgn_id, rgn_name, year, chi=value) %>%
  left_join(un_rgn, by="rgn_id")

chi_filter <- dplyr::filter(chi, rgn_name %in%
                       c("Dominican Republic",
                         "Jarvis Island",
                         "Singapore",
                         "Canada",
                         "Norway",
                         "Ghana",
                         "Bouvet Island")) %>%
  mutate(new_name = paste(chi_filter$rgn_name, chi_filter$georegion, sep="\n")) %>%
  mutate(label = if_else(year == max(year), as.character(new_name), NA_character_))

p <- ggplot(chi, aes(x=year, y=chi, color=georegion, group=rgn_name,
                     label=rgn_name)) +
  geom_line(alpha=0.3, size=0.3) +
  labs(y="Cumulative human impact", x="") +
  theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1, size=13),
        axis.text.y=element_text(size=13)) +
  geom_line(data=chi_filter, aes(x=year, y=chi, color=georegion, group=rgn_name), size=1, alpha=0.75) +
  #geom_text_repel(data=chi_filter, aes(label = label), na.rm=TRUE,  size=3, segment.color=NA, nudge_x=1, hjust=0, point.padding = NA, direction="y") +
  geom_text(data = chi_filter, aes(label = label, colour = georegion, x = 2013.2, y = chi), hjust = 0, size=3)+
  theme(legend.position="none") +
  xlim(2003, 2017)
# +
#   scale_x_continuous(breaks=c(2003, 2005, 2007, 2009, 2011, 2013)) 

p  
ggsave('impacts/figures/trend/chi_lineplot.jpg', height=6, width=6, units=c("in"))


gp <- plotly::ggplotly(p)
htmlwidgets::saveWidget(gp, "CHI_eez_line.html", selfcontained = TRUE)


```
# Heat map of EEZ CHI
```{r}
## heat map
plot_data <- read.csv("impacts/zonal_data_eez/eez_chi.csv") %>%
  dplyr::select(rgn_name, year, value)

avg <- plot_data %>%
  group_by(rgn_name) %>%
  summarize(average=mean(value))

plot_data <- plot_data %>%
  left_join(avg, by="rgn_name")

plot_data$rgn_name <- factor(plot_data$rgn_name, 
              levels = avg$rgn_name[order(avg$average, decreasing = TRUE)])


cols = rev(colorRampPalette(brewer.pal(11, 'Spectral'))(255)) # 

tmp <- ggplot(plot_data, aes(y=year, x=rgn_name, text=)) +
  geom_tile(aes(fill=value, 
      text=sprintf("region: %s \nyear: %s \npressure: %s" , rgn_name, year, round(value, 2))), color="white") +
  scale_fill_gradientn(colors=rev(brewer.pal(11, 'Spectral'))) +
  ylab("Year") + 
  xlab("Region") +
theme_bw() + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) 
  
tmp_plotly <- ggplotly(tmp, tooltip = "text")
htmlwidgets::saveWidget(widget=tmp_plotly, "eez_chi_heat.html", selfcontained = TRUE)


```


