---
title: "Comparing to previous CHI"
output: html_document
---

```{r setup}

library(rgdal)
library(raster)
library(dplyr)
library(tidyr)

source("https://raw.githubusercontent.com/OHI-Science/ohiprep_v2018/master/src/R/spatial_common.R")

cols = rev(colorRampPalette(brewer.pal(11, 'Spectral'))(255)) # rainbow color scheme
cols <- c(NA, cols)
```


Comparing current 2013 values with previous values.

```{r setup, include=FALSE}

## current data

pressures <- read.csv("impacts/zonal_data_eez/eez_impacts.csv") %>%
  mutate(rgn_name = gsub("Cura\x8dao", "Curacao", rgn_name),
         rgn_name = gsub("R\x8epublique du Congo", "Republique du Congo", rgn_name),
         rgn_name = gsub("R\x8eunion", "Reunion", rgn_name))

chi <- read.csv("impacts/zonal_data_eez/eez_chi.csv") %>%
  rename(chi = value) %>%
  select(-pressure) %>%
  arrange(year, chi)

ranks <- pressures %>%
  left_join(chi, by=c("rgn_id", "rgn_name", "year")) %>%
  arrange(year, -chi) %>%
  group_by(pressure) %>%
  mutate(pressure_num = n()) %>%
  ungroup() %>%
  filter(pressure_num == max(pressure_num)) %>%  ## cut pressures without all years of data
  select(-pressure_num)

## compare with previous CHI analysis
eez_2013 <- read.csv("../cia/ZonalExtractionData/withZero2NA/oneYearNorm_2013_eez_zeroData.csv") %>%
  filter(eez_nam != "Conflict Zone") %>%
  mutate(eez_nam = gsub("Cura\x8dao", "Curacao", eez_nam),
         eez_nam = gsub("R\x8epublique du Congo", "Republique du Congo", eez_nam),
         eez_nam = gsub("R\x8eunion", "Reunion", eez_nam)) %>%
  select(-sst) %>%
  rename(sst=layer)

eez_2013$eez_nam[eez_2013$eez_id==252] = "Halai'ib: Egypt-Sudan Disputed" 

eez_2013 <- eez_2013 %>%
  rename(rgn_name = eez_nam, chi_2013=global_cumulative_impact_2013_all_layers.gri) %>%
  rename(art_fish=artisanal_fishing, dem_dest=demersal_destructive_fishing,
         dem_nondest_hb=demersal_nondest_high_bycatch, 
         dem_nondest_lb=demersal_nondest_low_bycatch, direct_human=population,
         light=night_lights, pel_hb=pelagic_high_bycatch, pel_lb = pelagic_low_bycatch,
         nutrient=plumes_fert, organic=plumes_pest, oa=ocean_acidification) %>%
  dplyr::select(-eez_id, -eez_key, -sov_id, -sov_nam, -eez_iso3) %>% 
  gather(pressure, value_2013, c(-rgn_name, -chi_2013)) %>%
  mutate(pressure = gsub("_combo", "", pressure)) 

eez_2013_crop <- filter(eez_2013, pressure %in% ranks$pressure) %>%
  group_by(rgn_name) %>%
  mutate(chi_2013_crop = sum(value_2013))


compare <- ranks %>%
  left_join(eez_2013_crop, c("rgn_name", "pressure")) %>%
  filter(year==2013) %>%
  rowwise() %>%
  mutate(dif_pressure = value - value_2013)

compare %>%
  group_by(pressure) %>%
  summarize(mean_diff = mean(dif_pressure, na.rm=TRUE),
            sd_diff =sd(dif_pressure, na.rm=TRUE))

plot(chi ~ chi_2013, data=compare)
abline(0, 1, col="red")

plot(chi ~ chi_2013_crop, data=compare)
abline(0, 1, col="red")


plot_chi <- function(pressure="art_fish"){
  compare_pressure <- compare[compare$pressure == pressure, ]
  plot(value ~ value_2013, data=compare_pressure, main = unique(pressure), ylab="current value", xlab="old value")
  abline(0, 1, col="red")
}

plot_chi_log <- function(pressure="art_fish"){
  compare_pressure <- compare[compare$pressure == pressure, ]
  plot(log(value) ~ log(value_2013), data=compare_pressure, main = unique(pressure), ylab="current value", xlab="old value")
  abline(0, 1, col="red")
}

plot_chi("art_fish") #ok
plot_chi("dem_dest") #ok
plot_chi("dem_nondest_hb") #ok
plot_chi("dem_nondest_lb") #ok
plot_chi("pel_lb") #ok
plot_chi("pel_hb") #ok
plot_chi("shipping") #ok
plot_chi_log("direct_human") #ok
plot_chi_log("light") #ok
plot_chi_log("nutrient") #ok
plot_chi_log("organic") #ok
plot_chi("slr") 
plot_chi("sst")
plot_chi("oa") #ok

```


### SST 

```{r}
#new
diffs <- list.files(file.path(dir_M, 'git-annex/impact_acceleration/stressors/sst/int'), pattern = 'sst_diff', full.names=TRUE)
sst <- raster(diffs[21])
plot(sst)

#old
old <- raster(file.path(dir_M, 'marine_threats/impact_layers_2013_redo/impact_layers/final_impact_layers/threats_2013_interim/new_layers/sst/gcs_nontrans_unclipped/sst.tif'))
old[old<0] <- 0

sst_proj <- projectRaster(sst, old, over=TRUE, method="ngb", progress="text")
sst_proj[sst_proj<0] <- 0
sst_proj_mask <- mask(sst_proj, old)

plot(old, sst_proj_mask, xlab="old", ylab="new")
abline(0,1, col="red")

new_log <- calc(sst_proj_mask, fun=function(x){log(x+1)})
old_log <- calc(old, fun=function(x){log(x+1)})

projectRaster(new_log, ocean, over=TRUE, method="ngb", filename=file.path(dir_M, "git-annex/impact_acceleration/data_check/sst_new_log.tif"), progress="text", overwrite=TRUE)

projectRaster(old_log, ocean, over=TRUE, method="ngb", filename=file.path(dir_M, "git-annex/impact_acceleration/data_check/sst_old_log.tif"), progress="text", overwrite=TRUE)

new_log <- raster(file.path(dir_M, "git-annex/impact_acceleration/data_check/sst_new_log.tif"))
old_log <- raster(file.path(dir_M, "git-annex/impact_acceleration/data_check/sst_old_log.tif"))



```

