---
title: "wastewater: extracting eez regions"
output: html_document
---

```{r}

library(RColorBrewer)

library(raster)
library(rgdal)

library(dplyr)
library(stringr)

library(parallel)
library(foreach)
library(doParallel)

library(here)

source("https://raw.githubusercontent.com/OHI-Science/ohiprep_v2019/gh-pages/workflow/R/common.R")
ohi_rasters()
region_data()

cols <- rev(colorRampPalette(brewer.pal(11, 'Spectral'))(255)) # rainbow color scheme
cols <- cols[150:255]

```


Extract data

```{r}
# r <- raster(ncol=360, nrow=180, xmx=180, xmn=-180, ymn=-90, ymx=90)
# plot(area(r))

ww <- list.files(file.path(dir_M, "git-annex/land-based/wastewater/output/no_log_data/stressor_impact"), full=TRUE)
ww <- raster(ww)
#chi_stack <- stack(chi)

## full eez
ww_eez <- zonal(ww, zones, fun="mean", progress="text", na.rm=TRUE)


## 3nm
rgns_3nm <- raster::raster(file.path(dir_M, "git-annex/globalprep/spatial/v2018/rgns_3nm_offshore_mol.tif"))
plot(rgns_3nm)
ww_3nm <- zonal(ww, rgns_3nm, fun="mean", progress="text", na.rm=TRUE)

regions <- rgns_all %>%
  select(type_w_ant, rgn_id = rgn_ant_id, rgn_name) %>%
  filter(type_w_ant %in% c("eez", "eez-ccamlr", "fao"))

##
ww_data_df <- data.frame(ww_eez) %>%
  dplyr::select(zone, eez_avg=mean) %>%
  dplyr::left_join(data.frame(ww_3nm)) %>%
  dplyr::select(rgn_id=zone, eez_avg, nm3_avg=mean) %>%
  dplyr::left_join(regions, by="rgn_id")

#should have 254 regions, but only going to look at eezs, so this will end up as 220 regions


ww_data_df <- ww_data_df %>%
  dplyr::filter(type_w_ant == "eez") %>%
  dplyr::select(rgn_id, rgn_name, eez_avg, nm3_avg) %>%
  dplyr::arrange(nm3_avg)


```


Compare data to other pressures.
(realized I never extracted these particular data)
```{r}

## all impacts 2013 data
impact2013 <- list.files(file.path(dir_M, "git-annex/impact_acceleration/impact/stressor_impact"), pattern="2013", full.names=TRUE)

impact2013 <- grep("uv_2013|str_2013", impact2013, invert=TRUE, value=TRUE)

impact_stack <- stack(impact2013)

impacts_3nm <- zonal(impact_stack, rgns_3nm, fun="mean", progress="text", na.rm=TRUE)
write.csv(impacts_3nm, here("paper/zonal_data_eez/eez_3nm_2013_impacts.csv"), row.names=FALSE)


impacts_3nm <- read.csv(here("paper/zonal_data_eez/eez_3nm_2013_impacts.csv"))
impacts_all <- data.frame(impacts_3nm) %>%
  dplyr::rename(rgn_id=zone) %>%
  dplyr::left_join(ww_data_df)

## add in chi
chi <- read.csv(here("paper/zonal_data_eez/eez_3nm_chi.csv")) %>%
  dplyr::filter(year == 2013) %>%
  dplyr::select(rgn_id, chi_2103=value)

impacts_all <- impacts_all %>%
  left_join(chi, by="rgn_id")

write.csv(impacts_all, here("projects/wastewater/eez_3nm.csv"), row.names=FALSE)

```


Compare the data.
```{r}

impacts <- read.csv(here("projects/wastewater/eez_3nm.csv"))

library(ggplot2)


ggplot(impacts, aes(y=nm3_avg, x=nutrient_2013)) +
  geom_point(alpha=0.3, size=2.5) +
  theme_bw() + 
  labs(y="wastewater: nutrient impact", x="fertilizer: nutrient impact") +
  geom_abline(slope=1, intercept=0, color="red")

```