---
title: "Calc_quantiles"
output: html_document
---

Get the quantile data for stressor impacts and cumulative impacts.

## Loading packages

```{r}
#libraries
library(raster)
library(RColorBrewer)
library(sf)
library(dplyr)
library(doParallel)
library(foreach)
library(parallel)
library(tidyr)
library(stringr)
library(ggplot2)


source("https://raw.githubusercontent.com/OHI-Science/ohiprep_v2018/master/src/R/spatial_common.R")


```

## Individual impacts
```{r}

stressors <- list.files(file.path(dir_M, "git-annex/impact_acceleration/impact/stressor_impact"), 
                        full=TRUE)

registerDoParallel(4)
foreach(stress = stressors,.packages="dplyr") %dopar%{ # stress = stressors[1]
#for(stress in stressors){ # stress = stressors[1]
 st_tmp <- raster::raster(stress) 
 quants <- raster::quantile(st_tmp, c(0.01, 0.05, 0.5, 0.95, 0.99))
 quants_df <- data.frame(quants)
 quants_df$quant <- row.names(quants_df)
 quants_df$impact <- basename(stress)
 fn <- gsub(".tif", "", basename(stress))
 write.csv(quants_df, sprintf("impacts/quantiles/%s.csv", fn), row.names=FALSE)
}

```

## Cumulative impacts
```{r}
stressors <- list.files(file.path(dir_M, "git-annex/impact_acceleration/impact/cumulative_impact"), 
                          full=TRUE, pattern="chi")
  
registerDoParallel(4)
  foreach(stress = stressors,.packages="dplyr") %dopar%{
  #  for(stress in stressors){ # stress = stressors[1]
      st_tmp <- raster::raster(stress) 
      quants <- raster::quantile(st_tmp, c(0.01, 0.05, 0.5, 0.95, 0.99))
      quants_df <- data.frame(quants)
      quants_df$quant <- row.names(quants_df)
      quants_df$impact <- basename(stress)
      fn <- gsub(".tif", "", basename(stress))
      write.csv(quants_df, sprintf("impacts/quantiles/%s.csv", fn), row.names=FALSE)
    }
    
```  

## Organize the quantile data

```{r}

files <- list.files("paper/quantiles", full=TRUE, pattern=".csv")

filter_str <- function(stressor){ #stressor <- "art_fish"
stress_files <- grep(stressor, files, value=TRUE)

all_data <- c()
for (file in stress_files){ # file = stress_files[1]
  little_data <- read.csv(file)
  all_data <- rbind(all_data, little_data)
}

all_data$year <- as.numeric(str_sub(all_data$impact,-8,-5))
all_data
}

```

### Plot the data
```{r}

### Ocean acidification 
plot_data <- filter_str(stressor="oa") %>%
  mutate(quant = gsub("%", "", quant)) %>%
  mutate(quant = paste0("quant_", quant)) %>%
  filter(quant %in% c("quant_50", "quant_95", "quant_99"))

ggplot(plot_data, aes(x=year, y=quants, group=quant, col=quant)) +
  geom_point(size=3) +
  geom_line() +
  theme_bw() +
  labs(title = "Ocean acification")

##SST
plot_data <- filter_str(stressor="sst") %>%
  mutate(quant = gsub("%", "", quant)) %>%
  mutate(quant = paste0("quant_", quant)) %>%
  filter(quant %in% c("quant_50", "quant_95", "quant_99"))

ggplot(plot_data, aes(x=year, y=quants, group=quant, col=quant)) +
  geom_point(size=3) +
  geom_line() +
  theme_bw() +
  labs(title = "SST")

### Sea level rise
plot_data <- filter_str(stressor="slr") %>%
  mutate(quant = gsub("%", "", quant)) %>%
  mutate(quant = paste0("quant_", quant)) %>%
  filter(quant %in% c("quant_50", "quant_95", "quant_99"))

ggplot(plot_data, aes(x=year, y=quants, group=quant, col=quant)) +
  geom_point(size=3) +
  geom_line() +
  theme_bw() +
  labs(title = "Sea level rise")


## Artisanal fishing
plot_data <- filter_str(stressor="art_fish")  %>%
  mutate(quant = gsub("%", "", quant)) %>%
  mutate(quant = paste0("quant_", quant)) %>%
  filter(quant %in% c("quant_99"))

ggplot(plot_data, aes(x=year, y=quants, group=quant, col=quant)) +
  geom_point(size=3) +
  geom_line() +
  theme_bw() +
  labs(title = "artisanal fishing")

###Pelagic low bycatch
plot_data <- filter_str(stressor="pel_lb") %>%
  mutate(quant = gsub("%", "", quant)) %>%
  mutate(quant = paste0("quant_", quant)) %>%
  filter(quant %in% c("quant_50", "quant_95", "quant_99"))

ggplot(plot_data, aes(x=year, y=quants, group=quant, col=quant)) +
  geom_point(size=3) +
  geom_line() +
  theme_bw() +
  labs(title = "Pelagic low bycatch")

###Pelagic high bycatch
plot_data <- filter_str(stressor="pel_hb") %>%
  mutate(quant = gsub("%", "", quant)) %>%
  mutate(quant = paste0("quant_", quant)) %>%
  filter(quant %in% c("quant_50", "quant_95", "quant_99"))

ggplot(plot_data, aes(x=year, y=quants, group=quant, col=quant)) +
  geom_point(size=3) +
  geom_line() +
  theme_bw() +
  labs(title = "Pelagic high bycatch")

### Demersal destructive
plot_data <- filter_str(stressor="dem_des") %>%
  mutate(quant = gsub("%", "", quant)) %>%
  mutate(quant = paste0("quant_", quant)) %>%
  filter(quant %in% c("quant_50", "quant_95", "quant_99"))

ggplot(plot_data, aes(x=year, y=quants, group=quant, col=quant)) +
  geom_point(size=3) +
  geom_line() +
  theme_bw() +
  labs(title = "Demersal destructive")

### Demersal nondestructive high bycatch 
plot_data <- filter_str(stressor="dem_nondest_hb") %>%
  mutate(quant = gsub("%", "", quant)) %>%
  mutate(quant = paste0("quant_", quant)) %>%
  filter(quant %in% c("quant_50", "quant_95", "quant_99"))

ggplot(plot_data, aes(x=year, y=quants, group=quant, col=quant)) +
  geom_point(size=3) +
  geom_line() +
  theme_bw() +
  labs(title = "Demersal nondestructive high bycatch")



###Shipping
plot_data <- filter_str(stressor="shipping") %>%
  mutate(quant = gsub("%", "", quant)) %>%
  mutate(quant = paste0("quant_", quant)) %>%
  filter(quant %in% c("quant_50", "quant_95", "quant_99"))

ggplot(plot_data, aes(x=year, y=quants, group=quant, col=quant)) +
  geom_point(size=3) +
  geom_line() +
  theme_bw() +
  labs(title = "shipping")



### Organic pollution
plot_data <- filter_str(stressor="organic") %>%
  mutate(quant = gsub("%", "", quant)) %>%
  mutate(quant = paste0("quant_", quant)) %>%
  filter(quant %in% c("quant_50", "quant_95", "quant_99"))

ggplot(plot_data, aes(x=year, y=quants, group=quant, col=quant)) +
  geom_point(size=3) +
  geom_line() +
  theme_bw() +
  labs(title = "Landbased organic pollution")

### Nutrient pollution
plot_data <- filter_str(stressor="nutrient") %>%
  mutate(quant = gsub("%", "", quant)) %>%
  mutate(quant = paste0("quant_", quant)) %>%
  filter(quant %in% c("quant_50", "quant_95", "quant_99"))

ggplot(plot_data, aes(x=year, y=quants, group=quant, col=quant)) +
  geom_point(size=3) +
  geom_line() +
  theme_bw() +
  labs(title = "Landbased nutrient pollution")

### Light
plot_data <- filter_str(stressor="light") %>%
  mutate(quant = gsub("%", "", quant)) %>%
  mutate(quant = paste0("quant_", quant)) %>%
  filter(quant %in% c("quant_50", "quant_95", "quant_99"))

ggplot(plot_data, aes(x=year, y=quants, group=quant, col=quant)) +
  geom_point(size=3) +
  geom_line() +
  theme_bw() +
  labs(title = "Light pollution")

### Direct human
plot_data <- filter_str(stressor="human") %>%
  mutate(quant = gsub("%", "", quant)) %>%
  mutate(quant = paste0("quant_", quant)) %>%
  filter(quant %in% c("quant_50", "quant_95", "quant_99"))

ggplot(plot_data, aes(x=year, y=quants, group=quant, col=quant)) +
  geom_point(size=3) +
  geom_line() +
  theme_bw() +
  labs(title = "Human")

```
