---
title: "circle_plot"
output: html_document
---

```{r}

library(tidyverse)

```

# Trend for each 3nm eez impact circleplot

```{r 3nm_eez_trend_circleplot}

# UN georegions
UNgeorgn_nm <- read.csv("https://raw.githubusercontent.com/OHI-Science/ohiprep/master/globalprep/spatial/v2017/output/georegion_labels.csv") 
un_rgn <- UNgeorgn_nm %>%
  dplyr::select(rgn_id, georegion = r1_label)

# CHI for each region
chi <- read.csv("paper/zonal_data_eez/eez_chi_3nm_trend.csv") %>%
  dplyr::select(rgn_id, rgn_name, chi=value) %>%
  left_join(un_rgn, by="rgn_id")


# get georegion ranks based on mean chi values, and use to rank chi data
rank_georgn <- chi %>%
  group_by(georegion) %>%
  summarize(mean_chi = mean(chi),
            count = length(chi)) %>%
  arrange(mean_chi)

chi$georegion <- factor(chi$georegion, levels=rank_georgn$georegion)


### Organize the chi data and add a few extra variables to help plotting
# Including empty spaces to add a y-axes

rank_rgn <- chi %>%
  arrange(georegion, chi)

# add empty space
empty_bar <- 6
to_add <- data.frame(matrix(NA, empty_bar, ncol(rank_rgn)) )
colnames(to_add) = colnames(rank_rgn)
to_add$rgn_name <- as.character(1:empty_bar)
rank_rgn  <- rbind(to_add, rank_rgn)

# modify region names to be shorter
rank_rgn <- rank_rgn %>%
  mutate(rgn_name_short = rgn_name, 
         rgn_name_short = gsub("Islands", "Isl", rgn_name_short),
         rgn_name_short = gsub("Island", "Isl", rgn_name_short),
         rgn_name_short = gsub("Democratic", "Dem", rgn_name_short),
         rgn_name_short = gsub("Republic", "Rep", rgn_name_short),
         rgn_name_short = gsub("South", "S", rgn_name_short),
         rgn_name_short = gsub("American", "Am", rgn_name_short),
         rgn_name_short = gsub("the United States", "US", rgn_name_short),
         rgn_name_short = gsub("Territory", "Terr", rgn_name_short),
         rgn_name_short = gsub("Saint", "St", rgn_name_short),
         rgn_name_short = gsub(" and ", " & ", rgn_name_short),
         rgn_name_short = gsub("Republique", "Rep", rgn_name_short),
         rgn_name_short = gsub("Dem Rep of the", "Dem Rep of", rgn_name_short),
         rgn_name_short = gsub("Georgia and the", "Georgia and", rgn_name_short),
         rgn_name_short = gsub("St Vincent and the", "St Vincent and", rgn_name_short),
         rgn_name_short = gsub("Howland Isl & Baker Isl", "Howland & Baker Isl", rgn_name_short),
         rgn_name_short = gsub("Northern", "N", rgn_name_short), 
         rgn_name_short = gsub("Reunion", "Reunion   ", rgn_name_short))


# some code to orient the country labels
sequence_length = length(unique(rank_rgn$rgn_name))
first_sequence = c(1:(sequence_length%/%2)) 
second_sequence = c((sequence_length%/%2+1):sequence_length) 
first_angles = c(90 - 180/length(first_sequence) * first_sequence)
second_angles = c(-90 - 180/length(second_sequence) * second_sequence)

rank_rgn$angle <- c(first_angles,second_angles)
rank_rgn$hjust <- c(rep(0, length(first_sequence)), 
                    rep(1, length(second_sequence)))

# color for region labels
rank_rgn <- rank_rgn %>%
  mutate(rgn_name = factor(rgn_name, unique(rgn_name))) %>%
  mutate(georegion = factor(georegion, unique(georegion))) %>%
  mutate(color = "black") %>%
  mutate(color = ifelse(is.na(chi), "white", color))


########### marking georegions

# add column to identify when georegion changes
rgn_shift <- rank_rgn %>%
  mutate(georegion = ifelse(is.na(georegion), "tmp", georegion)) %>%
  mutate(georegion = as.factor(georegion)) %>%
  mutate(region_shift = as.numeric(georegion) - lag(as.numeric(georegion)), default=first(as.numeric(georegion)))

rgn_shift <- which(rgn_shift$region_shift > 0)
rgn_shift <- c(1, rgn_shift) -0.5
rgn_shift <- data.frame(rgn_shift_x=rgn_shift,
                        georegion = rank_georgn$georegion,
                        name_x= c(25, 51, 68, 90, 110, 145, 200), # 140
                        name_y=c(0.1, 0.1, 0.1, 0.12, 0.11, 0.1, 0.11))
rgn_shift <- rgn_shift %>%
  mutate(georegion = as.character(georegion)) %>%
  mutate(georegion = ifelse(georegion == "Latin America and the Caribbean", "Latin America and\nthe Caribbean",
                            georegion))

# get impact data
impacts <- read.csv("paper/zonal_data_eez/eez_3nm_impacts_trend.csv") %>%
  left_join(un_rgn)

# ## add some blanks to separate groups
to_add <-  data.frame( matrix(NA, empty_bar*nlevels(as.factor(impacts$pressure)), ncol(impacts)) )
colnames(to_add) <- colnames(impacts)
to_add$pressure <- rep(levels(as.factor(impacts$pressure)), each=empty_bar)
to_add$value <-  0
to_add$rgn_name <- as.character(rep(1:empty_bar, nlevels(as.factor(impacts$pressure)))) 

impacts <- rbind(to_add, impacts, to_add)


## rank of pressure categories
impacts %>%
  group_by(pressure) %>%
  summarize(mean = mean(value)) %>%
  arrange(mean)

pressure_name <- data.frame(pressure = c("sst", "slr", "oa", 
                                         "shipping",
                                         "light", "nutrient", "direct_human", "organic",
                                         "pel_hb", "dem_nondest_hb","pel_lb", 
                                         "dem_nondest_lb", "dem_dest", "art_fish"),
                            pressure_name = c("sst", "slr", "oa",
                                              "shipping", "light pollution", 
                                              "nutrient pollution", "direct human", "organic pollution",  
                                              "comm fish: pel hb", "comm fish: dem nondest hb", "comm fish: pel lb", 
                                              "comm fish: dem nondest lb", "comm fish: dem dest", "artisanal fishing"))

impacts <- impacts %>%
  left_join(pressure_name, by = "pressure")

check <- st_read("/home/shares/ohi/git-annex/land-based/wastewater-mar/raw_data/Usos_de _suelo_cuencas_Mar/Rio_Motagua/Clasificacion/Clasificacion_fin.shp")
head(check)

impacts$pressure_name <- factor(impacts$pressure_name, levels=rev(pressure_name$pressure_name))
impacts$rgn_name <- factor(impacts$rgn_name, levels=unique(rank_rgn$rgn_name))


library(beyonce)

myPalette <- c(beyonce_palette(18, 15, type=c("continuous"))[1:6],
               beyonce_palette(18, 25, type=c("continuous"))[15:18],
               beyonce_palette(18, 15, type=c("continuous"))[8],
               beyonce_palette(18, 20, type=c("continuous"))[16:19])


## some theme stuff to make the circle plot look nice

circle_theme <- theme(axis.line=element_blank(),
                      axis.text.y=element_blank(),
                      axis.ticks=element_blank(),
                      axis.title.x=element_blank(),
                      axis.title.y=element_blank(),
                      legend.position="none",
                      panel.background=element_blank(),
                      panel.border=element_blank(),
                      panel.grid.major=element_blank(),
                      panel.grid.minor=element_blank(),
                      plot.background=element_blank(),
                      axis.text.x = element_blank())

# circle plot
# https://www.r-graph-gallery.com/299-circular-stacked-barplot/
p <- ggplot(data=impacts, aes(x=rgn_name, y=value, fill=pressure_name)) + 
  geom_bar(stat="identity") +
  geom_errorbar(aes(x = 1, ymin = -0.13, ymax=0.25), alpha=0)  +
  geom_text(data=rank_rgn, aes(x=rgn_name, y=0.16, label=rgn_name_short, angle=angle, hjust=hjust, color=color), inherit.aes = FALSE) +
  geom_segment(x = 5, y = 0, xend = dim(rank_rgn)[1]+1, yend = 0, colour = "black", alpha=1, size=0.5) +
  geom_segment(x = 7, y = -0.05, xend = dim(rank_rgn)[1]-1, yend = -0.05, colour = "gray", alpha=1, size=0.5) +
  annotate("text", x = c(3,3,3,3), y = c(-0.05, 0, 0.05, 0.1), label = c(-0.05, 0, 0.05, 0.1), color="darkgrey", angle=-8, size=4) +
  scale_colour_identity() +
  scale_fill_manual(values=myPalette) +
  coord_polar() +
  geom_segment(data = rgn_shift, aes(x=rgn_shift_x, xend=rgn_shift_x, y=rep(-0.05, dim(rgn_shift)[1]), yend=rep(0.2, dim(rgn_shift)[1])), colour="gray", size=0.5, inherit.aes=FALSE) +
  geom_text(data=rgn_shift, aes(x=name_x, y=name_y, label=georegion), inherit.aes=FALSE, size=5) +
  #geom_point(data=chi, aes(y=chi, x=rgn_name), fill="black", shape="|", size=2.5) +
  circle_theme

p
ggsave('paper/figures/trend/eez_3nm_trend_circleplot.jpg', height=18, width=18, units=c("in"))

```
